twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        website:
            urlBase: '%website.urlBase%'
            name: '%website.name%'

when@test:
    twig:
        strict_variables: true
